/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Paper {
    title: string;
    subject: string;
    type: PaperType;
    year: bigint;
    classOrGrade: string;
    fileUrl: string;
}
export interface Tool {
    url: string;
    icon: string;
    name: string;
    description: string;
}
export interface Note {
    title: string;
    content: string;
    subject: string;
    createdAt: bigint;
    level: Level;
    classOrGrade: string;
}
export enum Level {
    school = "school",
    university = "university"
}
export enum PaperType {
    pyq = "pyq",
    sample = "sample"
}
export interface backendInterface {
    addPaper(title: string, type: PaperType, subject: string, classOrGrade: string, year: bigint, fileUrl: string): Promise<void>;
    createNote(title: string, content: string, classOrGrade: string, subject: string, level: Level): Promise<void>;
    getAllNotes(): Promise<Array<Note>>;
    getAllPapers(): Promise<Array<Paper>>;
    getAllTools(): Promise<Array<Tool>>;
    getNotesByClassOrGrade(classOrGrade: string): Promise<Array<Note>>;
    getNotesByLevel(level: Level): Promise<Array<Note>>;
    getNotesBySubject(subject: string): Promise<Array<Note>>;
    getPapersBySubject(subject: string): Promise<Array<Paper>>;
    getPapersByType(type: PaperType): Promise<Array<Paper>>;
    getPapersByYear(year: bigint): Promise<Array<Paper>>;
    initializeTools(): Promise<void>;
}
import type { Level as _Level, Note as _Note, Paper as _Paper, PaperType as _PaperType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPaper(arg0: string, arg1: PaperType, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPaper(arg0, to_candid_PaperType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPaper(arg0, to_candid_PaperType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Level): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, arg2, arg3, to_candid_Level_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, arg2, arg3, to_candid_Level_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPapers(): Promise<Array<Paper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPapers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPapers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTools();
            return result;
        }
    }
    async getNotesByClassOrGrade(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByClassOrGrade(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByClassOrGrade(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByLevel(arg0: Level): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByLevel(to_candid_Level_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByLevel(to_candid_Level_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesBySubject(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesBySubject(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesBySubject(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPapersBySubject(arg0: string): Promise<Array<Paper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapersBySubject(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapersBySubject(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPapersByType(arg0: PaperType): Promise<Array<Paper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapersByType(to_candid_PaperType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapersByType(to_candid_PaperType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPapersByYear(arg0: bigint): Promise<Array<Paper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapersByYear(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapersByYear(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeTools(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeTools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeTools();
            return result;
        }
    }
}
function from_candid_Level_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaperType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaperType): PaperType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Paper_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Paper): Paper {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subject: string;
    type: _PaperType;
    year: bigint;
    classOrGrade: string;
    fileUrl: string;
}): {
    title: string;
    subject: string;
    type: PaperType;
    year: bigint;
    classOrGrade: string;
    fileUrl: string;
} {
    return {
        title: value.title,
        subject: value.subject,
        type: from_candid_PaperType_n13(_uploadFile, _downloadFile, value.type),
        year: value.year,
        classOrGrade: value.classOrGrade,
        fileUrl: value.fileUrl
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    subject: string;
    createdAt: bigint;
    level: _Level;
    classOrGrade: string;
}): {
    title: string;
    content: string;
    subject: string;
    createdAt: bigint;
    level: Level;
    classOrGrade: string;
} {
    return {
        title: value.title,
        content: value.content,
        subject: value.subject,
        createdAt: value.createdAt,
        level: from_candid_Level_n8(_uploadFile, _downloadFile, value.level),
        classOrGrade: value.classOrGrade
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pyq: null;
} | {
    sample: null;
}): PaperType {
    return "pyq" in value ? PaperType.pyq : "sample" in value ? PaperType.sample : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    school: null;
} | {
    university: null;
}): Level {
    return "school" in value ? Level.school : "university" in value ? Level.university : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Paper>): Array<Paper> {
    return value.map((x)=>from_candid_Paper_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Level_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): _Level {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PaperType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaperType): _PaperType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaperType): {
    pyq: null;
} | {
    sample: null;
} {
    return value == PaperType.pyq ? {
        pyq: null
    } : value == PaperType.sample ? {
        sample: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): {
    school: null;
} | {
    university: null;
} {
    return value == Level.school ? {
        school: null
    } : value == Level.university ? {
        university: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
