/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaperType = IDL.Variant({ 'pyq' : IDL.Null, 'sample' : IDL.Null });
export const Level = IDL.Variant({
  'school' : IDL.Null,
  'university' : IDL.Null,
});
export const Note = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'level' : Level,
  'classOrGrade' : IDL.Text,
});
export const Paper = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'type' : PaperType,
  'year' : IDL.Nat,
  'classOrGrade' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const Tool = IDL.Record({
  'url' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPaper' : IDL.Func(
      [IDL.Text, PaperType, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'createNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Level],
      [],
      [],
    ),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
  'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getNotesByClassOrGrade' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getNotesByLevel' : IDL.Func([Level], [IDL.Vec(Note)], ['query']),
  'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getPapersBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Paper)], ['query']),
  'getPapersByType' : IDL.Func([PaperType], [IDL.Vec(Paper)], ['query']),
  'getPapersByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Paper)], ['query']),
  'initializeTools' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaperType = IDL.Variant({ 'pyq' : IDL.Null, 'sample' : IDL.Null });
  const Level = IDL.Variant({ 'school' : IDL.Null, 'university' : IDL.Null });
  const Note = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'level' : Level,
    'classOrGrade' : IDL.Text,
  });
  const Paper = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'type' : PaperType,
    'year' : IDL.Nat,
    'classOrGrade' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const Tool = IDL.Record({
    'url' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addPaper' : IDL.Func(
        [IDL.Text, PaperType, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Level],
        [],
        [],
      ),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
    'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getNotesByClassOrGrade' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getNotesByLevel' : IDL.Func([Level], [IDL.Vec(Note)], ['query']),
    'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getPapersBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Paper)], ['query']),
    'getPapersByType' : IDL.Func([PaperType], [IDL.Vec(Paper)], ['query']),
    'getPapersByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Paper)], ['query']),
    'initializeTools' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };