/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Level = { 'school' : null } |
  { 'university' : null };
export interface Note {
  'title' : string,
  'content' : string,
  'subject' : string,
  'createdAt' : bigint,
  'level' : Level,
  'classOrGrade' : string,
}
export interface Paper {
  'title' : string,
  'subject' : string,
  'type' : PaperType,
  'year' : bigint,
  'classOrGrade' : string,
  'fileUrl' : string,
}
export type PaperType = { 'pyq' : null } |
  { 'sample' : null };
export interface Tool {
  'url' : string,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface _SERVICE {
  'addPaper' : ActorMethod<
    [string, PaperType, string, string, bigint, string],
    undefined
  >,
  'createNote' : ActorMethod<
    [string, string, string, string, Level],
    undefined
  >,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllPapers' : ActorMethod<[], Array<Paper>>,
  'getAllTools' : ActorMethod<[], Array<Tool>>,
  'getNotesByClassOrGrade' : ActorMethod<[string], Array<Note>>,
  'getNotesByLevel' : ActorMethod<[Level], Array<Note>>,
  'getNotesBySubject' : ActorMethod<[string], Array<Note>>,
  'getPapersBySubject' : ActorMethod<[string], Array<Paper>>,
  'getPapersByType' : ActorMethod<[PaperType], Array<Paper>>,
  'getPapersByYear' : ActorMethod<[bigint], Array<Paper>>,
  'initializeTools' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];